# Generated by Django 4.0.1 on 2022-01-13 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brewery_name', models.CharField(max_length=60)),
                ('alcohol_percantage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.CharField(default='listed ingredients', max_length=60)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(default='spring water', editable=False, max_length=60)),
                ('hop', models.CharField(max_length=60)),
                ('malt', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='created_at')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewery_app.beer')),
            ],
        ),
    ]
