# Generated by Django 4.0.1 on 2022-01-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='beer_id',
        ),
    ]
