# Generated by Django 4.0.1 on 2022-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_app', '0002_rename_ingredients_ingredient_beer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='hop',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='malt',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
