# Generated by Django 4.0.1 on 2022-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_app', '0005_alter_beer_ingredient_water_alter_hop_beer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='ingredient_hop',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='ingredient_malt',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='ingredient_water',
        ),
        migrations.AlterField(
            model_name='water',
            name='name',
            field=models.CharField(default='spring water', max_length=60),
        ),
    ]
